---
title: "variability data: pairwise comparisons for ground truth"
output: html_document
---


First, read in the packages.  

```{r packages, echo = F, warning = F, message = F}
library(tidyverse)
library(bulletxtrctr)
library(x3ptools)
library(gridExtra)
library(randomForest)
```


## BARREL ORANGE  
Crosscut data already extracted  


```{r}
orange_sigs <- readRDS("../data/variability_scans/orange_123_sigs.rda")
```

## ORANGE, CONNORS BULLETS 123 for BASE
```{r}
orange_bullets_123 <- orange_sigs %>% filter(operator == "Connor", round == "Round 1", machine == "Sneox1") 
orange_b123_lands <- unique(orange_bullets_123$scan_id) 
orange_b123_comparisons <- data.frame(
  expand.grid(land1 = orange_b123_lands, land2 = orange_b123_lands), stringsAsFactors = FALSE)
orange_b123_comparisons <- orange_b123_comparisons %>% mutate(
  aligned = purrr::map2(.x = land1, .y = land2, .f = function(xx, yy) {
    land1 <- orange_bullets_123$sigs[orange_bullets_123$scan_id == xx][[1]]
    land2 <- orange_bullets_123$sigs[orange_bullets_123$scan_id == yy][[1]]
    land1$bullet <- "first-land"
    land2$bullet <- "second-land"
    
    sig_align(land1$sig, land2$sig)
  })
)

```


```{r}
orange_b123_comparisons <- orange_b123_comparisons %>% mutate(
  ccf0 = aligned %>% 
    purrr::map_dbl(.f = function(x) extract_feature_ccf(x$lands)),
  lag0 = aligned %>% 
    purrr::map_dbl(.f = function(x) extract_feature_lag(x$lands)),
  D0 = aligned %>% 
    purrr::map_dbl(.f = function(x) extract_feature_D(x$lands)),
  length0 = aligned %>% 
    purrr::map_dbl(.f = function(x) extract_feature_length(x$lands)),
  overlap0 = aligned %>% 
    purrr::map_dbl(.f = function(x) extract_feature_overlap(x$lands))
)

orange_b123_comparisons <- orange_b123_comparisons %>% mutate(
  striae = aligned %>% purrr::map(.f = sig_cms_max, span = 75) 
)
orange_b123_comparisons <- orange_b123_comparisons %>% mutate(
  cms_per_mm = purrr::map2(striae, aligned, .f = function(s, a) {
    extract_feature_cms_per_mm(s$lines, a$lands, resolution=0.645)
  }),
  matches0 = striae %>% purrr::map_dbl(.f = function(s) {
    bulletxtrctr:::extract_helper_feature_n_striae(s$lines, type = "peak", match = TRUE)
  }),
  mismatches0 = striae %>% purrr::map_dbl(.f = function(s) {
    bulletxtrctr:::extract_helper_feature_n_striae(s$lines, type = "peak", match = FALSE)
  })
  
)


orange_b123_comparisons <- orange_b123_comparisons %>% mutate(
  features = purrr::map2(.x = aligned, .y = striae, .f = extract_features_all, resolution = 0.645)
)

orange_b123_comparisons <- orange_b123_comparisons %>% mutate(
  legacy_features = purrr::map(striae, extract_features_all_legacy, resolution = 0.645)
)

orange_b123_comparisons <- orange_b123_comparisons %>% tidyr::unnest(legacy_features) 
# scale features before using them in the random forest, legacy features can be used out of the box
orange_b123_comparisons$rfscore <- predict(bulletxtrctr::rtrees, newdata = orange_b123_comparisons, type = "prob")[,2]

#head(comparisons_user)

#saveRDS(comparisons_user, "../data/user_meas_comparisons.rda")

rfscores_orange_b123 <- orange_b123_comparisons %>% select(land1, land2, rfscore)
saveRDS(rfscores_orange_b123, "../data/variability_scans/orange_b123_rfscores.rda")

```

```{r}
rfscores_orange_b123 <- readRDS("../data/variability_scans/orange_b123_rfscores.rda")
rfscores_orange_b123 <- rfscores_orange_b123 %>% 
  mutate(id_S1 = land1, id_S2 = land2) %>% 
  separate(col = id_S1, 
           into = c("Barrel_S1", "Land_S1", "Bullet_S1", 
                    "Operator_S1", "Machine_S1", "Round_S1"), sep = "-") %>% 
  separate(col = id_S2, 
           into = c("Barrel_S2", "Land_S2", "Bullet_S2", 
                    "Operator_S2", "Machine_S2", "Round_S2"), sep = "-")

rfscores_orange_b123 %>%
  filter(Bullet_S1 == "Bullet 1" & Machine_S1 == "Sneox1") %>% 
  ggplot(aes(x = Land_S2, y = land1, fill = rfscore)) +
  geom_tile() +
  scale_fill_gradient2(low = "grey80", high = "darkorange", 
                       midpoint = .5) +
  facet_wrap(~Bullet_S2 + Round_S2) +
  #xlab("Land A") +
  #ylab("Land B") +
  theme(aspect.ratio = 1, axis.text.x = element_text(angle =20))
```


## ORANGE BULLET 1

```{r}
orange_bullet1 <- orange_sigs %>% filter(bullet == "Bullet 1") 
orange_b1_lands <- unique(orange_bullet1$scan_id) 
orange_b1_comparisons <- data.frame(
  expand.grid(land1 = orange_b1_lands, land2 = orange_b1_lands), stringsAsFactors = FALSE)
orange_b1_comparisons <- orange_b1_comparisons %>% mutate(
  aligned = purrr::map2(.x = land1, .y = land2, .f = function(xx, yy) {
    land1 <- orange_bullet1$sigs[orange_bullet1$scan_id == xx][[1]]
    land2 <- orange_bullet1$sigs[orange_bullet1$scan_id == yy][[1]]
    land1$bullet <- "first-land"
    land2$bullet <- "second-land"
    
    sig_align(land1$sig, land2$sig)
  })
)

orange_b1_comparisons <- orange_b1_comparisons %>% mutate(
  ccf0 = aligned %>% 
    purrr::map_dbl(.f = function(x) extract_feature_ccf(x$lands)),
  lag0 = aligned %>% 
    purrr::map_dbl(.f = function(x) extract_feature_lag(x$lands)),
  D0 = aligned %>% 
    purrr::map_dbl(.f = function(x) extract_feature_D(x$lands)),
  length0 = aligned %>% 
    purrr::map_dbl(.f = function(x) extract_feature_length(x$lands)),
  overlap0 = aligned %>% 
    purrr::map_dbl(.f = function(x) extract_feature_overlap(x$lands))
)

orange_b1_comparisons <- orange_b1_comparisons %>% mutate(
  striae = aligned %>% purrr::map(.f = sig_cms_max, span = 75) 
)
orange_b1_comparisons <- orange_b1_comparisons %>% mutate(
  cms_per_mm = purrr::map2(striae, aligned, .f = function(s, a) {
    extract_feature_cms_per_mm(s$lines, a$lands, resolution=0.645)
  }),
  matches0 = striae %>% purrr::map_dbl(.f = function(s) {
    bulletxtrctr:::extract_helper_feature_n_striae(s$lines, type = "peak", match = TRUE)
  }),
  mismatches0 = striae %>% purrr::map_dbl(.f = function(s) {
    bulletxtrctr:::extract_helper_feature_n_striae(s$lines, type = "peak", match = FALSE)
  })
)

orange_b1_comparisons <- orange_b1_comparisons %>% mutate(
  features = purrr::map2(.x = aligned, .y = striae, .f = extract_features_all, resolution = 0.645)
)

orange_b1_comparisons <- orange_b1_comparisons %>% mutate(
  legacy_features = purrr::map(striae, extract_features_all_legacy, resolution = 0.645)
)

orange_b1_comparisons <- orange_b1_comparisons %>% tidyr::unnest(legacy_features) 
# scale features before using them in the random forest, legacy features can be used out of the box
orange_b1_comparisons$rfscore <- predict(bulletxtrctr::rtrees, newdata = orange_b1_comparisons, type = "prob")[,2]

#head(comparisons_user)

#saveRDS(comparisons_user, "../data/user_meas_comparisons.rda")

rfscores_orange_b1 <- orange_b1_comparisons %>% select(land1, land2, rfscore)
saveRDS(rfscores_orange_b1, "../data/variability_scans/orange_b1_rfscores.rda")
```


## ORANGE BULLET 2

```{r}
orange_bullet2 <- orange_sigs %>% filter(bullet == "Bullet 2") 
orange_b2_lands <- unique(orange_bullet2$scan_id) 
orange_b2_comparisons <- data.frame(
  expand.grid(land1 = orange_b2_lands, land2 = orange_b2_lands), stringsAsFactors = FALSE)
orange_b2_comparisons <- orange_b2_comparisons %>% mutate(
  aligned = purrr::map2(.x = land1, .y = land2, .f = function(xx, yy) {
    land1 <- orange_bullet2$sigs[orange_bullet2$scan_id == xx][[1]]
    land2 <- orange_bullet2$sigs[orange_bullet2$scan_id == yy][[1]]
    land1$bullet <- "first-land"
    land2$bullet <- "second-land"
    
    sig_align(land1$sig, land2$sig)
  })
)

orange_b2_comparisons <- orange_b2_comparisons %>% mutate(
  ccf0 = aligned %>% 
    purrr::map_dbl(.f = function(x) extract_feature_ccf(x$lands)),
  lag0 = aligned %>% 
    purrr::map_dbl(.f = function(x) extract_feature_lag(x$lands)),
  D0 = aligned %>% 
    purrr::map_dbl(.f = function(x) extract_feature_D(x$lands)),
  length0 = aligned %>% 
    purrr::map_dbl(.f = function(x) extract_feature_length(x$lands)),
  overlap0 = aligned %>% 
    purrr::map_dbl(.f = function(x) extract_feature_overlap(x$lands))
)

orange_b2_comparisons <- orange_b2_comparisons %>% mutate(
  striae = aligned %>% purrr::map(.f = sig_cms_max, span = 75) 
)
orange_b2_comparisons <- orange_b2_comparisons %>% mutate(
  cms_per_mm = purrr::map2(striae, aligned, .f = function(s, a) {
    extract_feature_cms_per_mm(s$lines, a$lands, resolution=0.645)
  }),
  matches0 = striae %>% purrr::map_dbl(.f = function(s) {
    bulletxtrctr:::extract_helper_feature_n_striae(s$lines, type = "peak", match = TRUE)
  }),
  mismatches0 = striae %>% purrr::map_dbl(.f = function(s) {
    bulletxtrctr:::extract_helper_feature_n_striae(s$lines, type = "peak", match = FALSE)
  })
)

orange_b2_comparisons <- orange_b2_comparisons %>% mutate(
  features = purrr::map2(.x = aligned, .y = striae, .f = extract_features_all, resolution = 0.645)
)

orange_b2_comparisons <- orange_b2_comparisons %>% mutate(
  legacy_features = purrr::map(striae, extract_features_all_legacy, resolution = 0.645)
)

orange_b2_comparisons <- orange_b2_comparisons %>% tidyr::unnest(legacy_features) 
# scale features before using them in the random forest, legacy features can be used out of the box
orange_b2_comparisons$rfscore <- predict(bulletxtrctr::rtrees, newdata = orange_b2_comparisons, type = "prob")[,2]

#head(comparisons_user)

#saveRDS(comparisons_user, "../data/user_meas_comparisons.rda")

rfscores_orange_b2 <- orange_b2_comparisons %>% select(land1, land2, rfscore)
saveRDS(rfscores_orange_b2, "../data/variability_scans/orange_b2_rfscores.rda")
```

## ORANGE BULLET 3

```{r}
orange_bullet3 <- orange_sigs %>% filter(bullet == "Bullet 3") 
orange_b3_lands <- unique(orange_bullet3$scan_id) 
orange_b3_comparisons <- data.frame(
  expand.grid(land1 = orange_b3_lands, land2 = orange_b3_lands), stringsAsFactors = FALSE)
orange_b3_comparisons <- orange_b3_comparisons %>% mutate(
  aligned = purrr::map2(.x = land1, .y = land2, .f = function(xx, yy) {
    land1 <- orange_bullet3$sigs[orange_bullet3$scan_id == xx][[1]]
    land2 <- orange_bullet3$sigs[orange_bullet3$scan_id == yy][[1]]
    land1$bullet <- "first-land"
    land2$bullet <- "second-land"
    
    sig_align(land1$sig, land2$sig)
  })
)

orange_b3_comparisons <- orange_b3_comparisons %>% mutate(
  ccf0 = aligned %>% 
    purrr::map_dbl(.f = function(x) extract_feature_ccf(x$lands)),
  lag0 = aligned %>% 
    purrr::map_dbl(.f = function(x) extract_feature_lag(x$lands)),
  D0 = aligned %>% 
    purrr::map_dbl(.f = function(x) extract_feature_D(x$lands)),
  length0 = aligned %>% 
    purrr::map_dbl(.f = function(x) extract_feature_length(x$lands)),
  overlap0 = aligned %>% 
    purrr::map_dbl(.f = function(x) extract_feature_overlap(x$lands))
)

orange_b3_comparisons <- orange_b3_comparisons %>% mutate(
  striae = aligned %>% purrr::map(.f = sig_cms_max, span = 75) 
)
orange_b3_comparisons <- orange_b3_comparisons %>% mutate(
  cms_per_mm = purrr::map2(striae, aligned, .f = function(s, a) {
    extract_feature_cms_per_mm(s$lines, a$lands, resolution=0.645)
  }),
  matches0 = striae %>% purrr::map_dbl(.f = function(s) {
    bulletxtrctr:::extract_helper_feature_n_striae(s$lines, type = "peak", match = TRUE)
  }),
  mismatches0 = striae %>% purrr::map_dbl(.f = function(s) {
    bulletxtrctr:::extract_helper_feature_n_striae(s$lines, type = "peak", match = FALSE)
  })
)

orange_b3_comparisons <- orange_b3_comparisons %>% mutate(
  features = purrr::map2(.x = aligned, .y = striae, .f = extract_features_all, resolution = 0.645)
)

orange_b3_comparisons <- orange_b3_comparisons %>% mutate(
  legacy_features = purrr::map(striae, extract_features_all_legacy, resolution = 0.645)
)

orange_b3_comparisons <- orange_b3_comparisons %>% tidyr::unnest(legacy_features) 
# scale features before using them in the random forest, legacy features can be used out of the box
orange_b3_comparisons$rfscore <- predict(bulletxtrctr::rtrees, newdata = orange_b3_comparisons, type = "prob")[,2]

#head(comparisons_user)

#saveRDS(comparisons_user, "../data/user_meas_comparisons.rda")

rfscores_orange_b3 <- orange_b3_comparisons %>% select(land1, land2, rfscore)
saveRDS(rfscores_orange_b3, "../data/variability_scans/orange_b3_rfscores.rda")
```




## SCORE VIZ FOR ESTABLISHING GROUND TRUTH  


```{r}
orange_sigs <- readRDS("../data/variability_scans/orange_123_sigs.rda")

orange_lands <- data.frame(scan_id = unique(orange_sigs$scan_id))

orange_lands <- orange_lands %>% mutate(scan = scan_id) %>% separate(scan, into = c("barrel", "land", "bullet", "operator", "machine", "round"), sep = "-")
#write_csv(orange_lands, "../data/variability_scans/orange_gt.csv")
```


```{r}
rfscores_orange_b1 <- readRDS("../data/variability_scans/orange_b1_rfscores.rda")
rfscores_orange_b1 <- rfscores_orange_b1 %>% 
  mutate(id_S1 = land1, id_S2 = land2) %>% 
  separate(col = id_S1, 
           into = c("barrel_S1", "land_S1", "bullet_S1", 
                    "operator_S1", "machine_S1", "round_S1"), sep = "-") %>% 
  separate(col = id_S2, 
           into = c("barrel_S2", "land_S2", "bullet_S2", 
                    "operator_S2", "machine_S2", "round_S2"), sep = "-")
```

The base land is "Connor - Bullet 1 - Sneox1 - Round 1 - LAND 1"


## ALLISON

```{r, echo = F, warning = F, message = F}
rfscores_orange_b1 %>%
  filter(operator_S1 == "Connor" & operator_S2 == "Allison") %>% 
  filter(round_S1 == "Round 1", machine_S1 == "Sneox1") %>% 
  ggplot(aes(x = land_S2, y = land1, fill = rfscore)) +
  geom_tile() +
  scale_fill_gradient2(low = "grey80", high = "darkorange", 
                       midpoint = .5) +
  facet_wrap(~machine_S2 + round_S2, nrow = 1) +
  #xlab("Land A") +
  #ylab("Land B") +
  theme(aspect.ratio = 1, axis.text.x = element_text(angle =20))
```

## ANYESHA

```{r, echo = F, warning = F, message = F}
rfscores_orange_b1 %>%
  filter(operator_S1 == "Connor" & operator_S2 == "Anyesha") %>% 
  filter(round_S1 == "Round 1", machine_S1 == "Sneox1") %>% 
  ggplot(aes(x = land_S2, y = land1, fill = rfscore)) +
  geom_tile() +
  scale_fill_gradient2(low = "grey80", high = "darkorange", 
                       midpoint = .5) +
  facet_wrap(~machine_S2 + round_S2, nrow = 1) +
  #xlab("Land A") +
  #ylab("Land B") +
  theme(aspect.ratio = 1, axis.text.x = element_text(angle =20))
```


## CARLEY

```{r, echo = F, warning = F, message = F}
rfscores_orange_b1 %>%
  filter(operator_S1 == "Connor" & operator_S2 == "Carley") %>% 
  filter(round_S1 == "Round 1", machine_S1 == "Sneox1") %>% 
  ggplot(aes(x = land_S2, y = land1, fill = rfscore)) +
  geom_tile() +
  scale_fill_gradient2(low = "grey80", high = "darkorange", 
                       midpoint = .5) +
  facet_wrap(~machine_S2 + round_S2, nrow = 1) +
  #xlab("Land A") +
  #ylab("Land B") +
  theme(aspect.ratio = 1, axis.text.x = element_text(angle =20))
```

## CONNOR

```{r, echo = F, warning = F, message = F}
rfscores_orange_b1 %>%
  filter(operator_S1 == "Connor" & operator_S2 == "Connor") %>% 
  filter(round_S1 == "Round 1", machine_S1 == "Sneox1") %>% 
  ggplot(aes(x = land_S2, y = land1, fill = rfscore)) +
  geom_tile() +
  scale_fill_gradient2(low = "grey80", high = "darkorange", 
                       midpoint = .5) +
  facet_wrap(~machine_S2 + round_S2, nrow = 1) +
  #xlab("Land A") +
  #ylab("Land B") +
  theme(aspect.ratio = 1, axis.text.x = element_text(angle =20))
```

## MYA

```{r, echo = F, warning = F, message = F}
rfscores_orange_b1 %>%
  filter(operator_S1 == "Connor" & operator_S2 == "Mya") %>% 
  filter(round_S1 == "Round 1", machine_S1 == "Sneox1") %>% 
  ggplot(aes(x = land_S2, y = land1, fill = rfscore)) +
  geom_tile() +
  scale_fill_gradient2(low = "grey80", high = "darkorange", 
                       midpoint = .5) +
  facet_wrap(~machine_S2 + round_S2, nrow = 1) +
  #xlab("Land A") +
  #ylab("Land B") +
  theme(aspect.ratio = 1, axis.text.x = element_text(angle =20))
```





