---
title: "orange rounds 123 signature viz"
output: html_document
---


```{r packages, echo = F, warning = F, message = F}
library(tidyverse)
library(gridExtra)
library(lme4)
library(bulletxtrctr)
```


First, we want to add our "unique_id" for each land to the signature data, so we can group them by that and align the lands. 
```{r}
orange_sigs <- readRDS("../data/variability_scans/Orange_all_sigs.rda")
orange_sigs <- orange_sigs %>% 
  select(scan_id, sigs)
head(orange_sigs)

orange_gt <- read_csv("../data/variability_scans/orange_gt.csv")
orange_sigs <- full_join(orange_sigs, orange_gt)

orange_ops <- read_csv("../data/variability_scans/operators_blind.csv")
orange_sigs <- left_join(orange_sigs, orange_ops)
head(orange_sigs)
```




```{r}
bl_o1 <- orange_sigs %>% filter(unique_id == "BL O-1")
bl_o1 <- bl_o1 %>% mutate(sigs_aligned = purrr::map(sigs, .f = function(row){
  align <- sig_align(bl_o1$sigs[[1]]$sig, row$sig)
  lands <- align$lands
  lands <- lands[!is.na(lands$sig1),]
  lands$x_aligned <- 1:(dim(lands)[1])
  lands
}))

#blo1_long <- bl_o1 %>% unnest(sigs_aligned)

#blo1_long %>% 
#  filter(operator != "Mya") %>%
#  ggplot() + 
#  geom_line(aes(x = x_aligned, y = sig2, group = scan_id, color = factor(bullet)), alpha = 0.7) + 
#  geom_line(aes(x = x_aligned, y = sig1)) + 
#  theme_bw() 

bl_o2 <- orange_sigs %>% filter(unique_id == "BL O-2")
bl_o2 <- bl_o2 %>% mutate(sigs_aligned = purrr::map(sigs, .f = function(row){
  align <- sig_align(bl_o2$sigs[[1]]$sig, row$sig)
  lands <- align$lands
  lands <- lands[!is.na(lands$sig1),]
  lands$x_aligned <- 1:(dim(lands)[1])
  lands
}))


bl_o3 <- orange_sigs %>% filter(unique_id == "BL O-3")
bl_o3 <- bl_o3 %>% mutate(sigs_aligned = purrr::map(sigs, .f = function(row){
  align <- sig_align(bl_o3$sigs[[1]]$sig, row$sig)
  lands <- align$lands
  lands <- lands[!is.na(lands$sig1),]
  lands$x_aligned <- 1:(dim(lands)[1])
  lands
}))

bl_o4 <- orange_sigs %>% filter(unique_id == "BL O-4")
bl_o4 <- bl_o4 %>% mutate(sigs_aligned = purrr::map(sigs, .f = function(row){
  align <- sig_align(bl_o4$sigs[[1]]$sig, row$sig)
  lands <- align$lands
  lands <- lands[!is.na(lands$sig1),]
  lands$x_aligned <- 1:(dim(lands)[1])
  lands
}))

bl_o5 <- orange_sigs %>% filter(unique_id == "BL O-5")
bl_o5 <- bl_o5 %>% mutate(sigs_aligned = purrr::map(sigs, .f = function(row){
  align <- sig_align(bl_o5$sigs[[1]]$sig, row$sig)
  lands <- align$lands
  lands <- lands[!is.na(lands$sig1),]
  lands$x_aligned <- 1:(dim(lands)[1])
  lands
}))

bl_o6 <- orange_sigs %>% filter(unique_id == "BL O-6")
bl_o6 <- bl_o6 %>% mutate(sigs_aligned = purrr::map(sigs, .f = function(row){
  ## grab one of connor's scans as base, this BL has tank rash/breakoff on 2 of 3 bullets
  align <- sig_align(bl_o6$sigs[[57]]$sig, row$sig) 
  lands <- align$lands
  lands <- lands[!is.na(lands$sig1),]
  lands$x_aligned <- 1:(dim(lands)[1])
  lands
}))

```


```{r, echo = F, warning = F, message = F}
barrelo <- rbind(bl_o1, bl_o2, bl_o3, bl_o4, bl_o5, bl_o6)
saveRDS(barrelo, "../data/variability_scans/orange_aligned_sigs.rda")

bo_long <- barrelo %>% unnest(sigs_aligned)
head(bo_long)


bo_long %>% 
  filter(abs(sig2) <= 15) %>%
  ggplot() + 
  geom_line(aes(x = x_aligned, y = sig2, group = scan_id, color = factor(operator_code)), alpha = 0.7) + 
  geom_line(aes(x = x_aligned, y = sig1), alpha = 0.8) + 
  theme_bw() + 
  facet_wrap(~unique_id, nrow = 2) + 
  labs(title = "Barrel Orange")


bo_long %>% 
  filter(abs(sig2) <= 15) %>%
  filter(unique_id != "BL O-6", operator != "Mya") %>%
  ggplot() + 
  geom_line(aes(x = x_aligned, y = sig2, group = scan_id, color = factor(bullet)), alpha = 0.7) + 
  geom_line(aes(x = x_aligned, y = sig1), alpha = 0.8) + 
  theme_bw() + 
  facet_grid(machine~unique_id) + 
  labs(title = "Barrel Orange")


bo_long %>% 
  filter(abs(sig2) <= 15) %>%
  ggplot() + 
  geom_line(aes(x = x_aligned, y = sig2, group = scan_id, color = factor(machine)), alpha = 0.7) + 
  geom_line(aes(x = x_aligned, y = sig1), alpha = 0.8) + 
  theme_bw() + 
  facet_grid(operator_code~unique_id) + 
  labs(title = "Barrel Orange")

```


```{r}
bo_long %>%
  filter(unique_id == "BL O-1") %>%
  ggplot() + 
  geom_line(aes(x = x_aligned, y = sig2, group = scan_id, color = factor(round)), alpha = 0.7) + 
  geom_line(aes(x = x_aligned, y = sig1), alpha = 0.7) + 
  theme_bw() + 
  facet_grid(operator_code~bullet) + 
  labs(title = "Barrel Orange Land 1")

bo_long %>%
  filter(unique_id == "BL O-2") %>%
  ggplot() + 
  geom_line(aes(x = x_aligned, y = sig2, group = scan_id, color = factor(round)), alpha = 0.7) + 
  geom_line(aes(x = x_aligned, y = sig1), alpha = 0.7) + 
  theme_bw() + 
  facet_grid(operator_code~bullet) + 
  labs(title = "Barrel Orange Land 2")

bo_long %>%
  filter(unique_id == "BL O-3") %>%
  ggplot() + 
  geom_line(aes(x = x_aligned, y = sig2, group = scan_id, color = factor(round)), alpha = 0.7) + 
  geom_line(aes(x = x_aligned, y = sig1), alpha = 0.7) + 
  theme_bw() + 
  facet_grid(operator_code~bullet) + 
  labs(title = "Barrel Orange Land 3")

bo_long %>%
  filter(unique_id == "BL O-4") %>%
  ggplot() + 
  geom_line(aes(x = x_aligned, y = sig2, group = scan_id, color = factor(round)), alpha = 0.7) + 
  geom_line(aes(x = x_aligned, y = sig1), alpha = 0.7) + 
  theme_bw() + 
  facet_grid(operator_code~bullet) + 
  labs(title = "Barrel Orange Land 4")

bo_long %>%
  filter(unique_id == "BL O-5") %>%
  ggplot() + 
  geom_line(aes(x = x_aligned, y = sig2, group = scan_id, color = factor(round)), alpha = 0.7) + 
  geom_line(aes(x = x_aligned, y = sig1), alpha = 0.7) + 
  theme_bw() + 
  facet_grid(operator_code~bullet) + 
  labs(title = "Barrel Orange Land 5")

bo_long %>%
  filter(unique_id == "BL O-6") %>%
  filter(abs(sig2) <= 20) %>%
  ggplot() + 
  geom_line(aes(x = x_aligned, y = sig2, group = scan_id, color = factor(round)), alpha = 0.7) + 
  geom_line(aes(x = x_aligned, y = sig1), alpha = 0.7) + 
  theme_bw() + 
  facet_grid(operator_code~bullet) + 
  labs(title = "Barrel Orange Land 6")


```

```{r}
bo_long %>%
  filter(unique_id == "BL O-1", sig2 <= 5) %>%
  group_by(x_aligned, bullet) %>%
  mutate(mean_bullet = mean(sig2, na.rm = T), resid_bullet = sig2 - mean_bullet) %>%
  ungroup() %>%
  ggplot() + 
  geom_line(aes(x = x_aligned, y = resid_bullet, group = scan_id, color = factor(round)), alpha = 0.7) + 
  geom_hline(yintercept = 0) + 
  #geom_line(aes(x = x_aligned, y = sig1), alpha = 0.7) + 
  theme_bw() + 
  facet_grid(operator_code~bullet) + 
  labs(title = "Barrel Orange Land 1")
```




```{r}
bo_long %>%
  filter(unique_id == "BL O-1") %>%
  group_by(operator_code, x_aligned) %>%
  mutate(operator_mean = mean(sig2, na.rm = T)) %>%
  ungroup() %>%
  ggplot() + 
  geom_line(aes(x = x_aligned, y = sig2, group = scan_id, color = factor(operator_code)), alpha = 0.7) + 
  geom_line(aes(x = x_aligned, y = operator_mean, group = operator_code), alpha = 0.7) + 
  theme_bw() + 
  #facet_wrap(~bullet, nrow = 3) + 
  labs(title = "Barrel Orange Land 1", x = "Relative X Location", y = "Signature Height") + 
  scale_color_discrete(name = "Operator ID")

bo_long %>%
  filter(unique_id == "BL O-2") %>%
  group_by(operator_code, x_aligned) %>%
  mutate(operator_mean = mean(sig2, na.rm = T)) %>%
  ungroup() %>%
  ggplot() + 
  geom_line(aes(x = x_aligned, y = sig2, group = scan_id, color = factor(operator_code)), alpha = 0.7) + 
  geom_line(aes(x = x_aligned, y = operator_mean, group = operator_code), alpha = 0.7) + 
  theme_bw() + 
  #facet_wrap(~bullet, nrow = 3) + 
  labs(title = "Barrel Orange Land 2", x = "Relative X Location", y = "Signature Height") + 
  scale_color_discrete(name = "Operator ID")

bo_long %>%
  filter(unique_id == "BL O-3") %>%
  filter(sig2 > -5, x_aligned < 2600, x_aligned > 10) %>%
  group_by(operator_code, x_aligned) %>%
  mutate(operator_mean = mean(sig2, na.rm = T)) %>%
  ungroup() %>%
  ggplot() + 
  geom_line(aes(x = x_aligned, y = sig2, group = scan_id, color = factor(operator_code)), alpha = 0.7) + 
  geom_line(aes(x = x_aligned, y = operator_mean, group = operator_code), alpha = 0.7) + 
  theme_bw() + 
  #facet_wrap(~bullet, nrow = 3) + 
  labs(title = "Barrel Orange Land 3", x = "Relative X Location", y = "Signature Height") + 
  scale_color_discrete(name = "Operator ID")

bo_long %>%
  filter(unique_id == "BL O-4") %>%
  group_by(operator_code, x_aligned) %>%
  mutate(operator_mean = mean(sig2, na.rm = T)) %>%
  ungroup() %>%
  ggplot() + 
  geom_line(aes(x = x_aligned, y = sig2, group = scan_id, color = factor(operator_code)), alpha = 0.7) + 
  geom_line(aes(x = x_aligned, y = operator_mean, group = operator_code), alpha = 0.7) + 
  theme_bw() + 
  #facet_wrap(~bullet, nrow = 3) + 
  labs(title = "Barrel Orange Land 4", x = "Relative X Location", y = "Signature Height") + 
  scale_color_discrete(name = "Operator ID")

bo_long %>%
  filter(unique_id == "BL O-5") %>%
  group_by(operator_code, x_aligned) %>%
  mutate(operator_mean = mean(sig2, na.rm = T)) %>%
  ungroup() %>%
  ggplot() + 
  geom_line(aes(x = x_aligned, y = sig2, group = scan_id, color = factor(operator_code)), alpha = 0.7) + 
  geom_line(aes(x = x_aligned, y = operator_mean, group = operator_code), alpha = 0.7) + 
  theme_bw() + 
  #facet_wrap(~bullet, nrow = 3) + 
  labs(title = "Barrel Orange Land 5", x = "Relative X Location", y = "Signature Height") + 
  scale_color_discrete(name = "Operator ID")

bo_long %>%
  filter(unique_id == "BL O-6") %>%
  group_by(operator_code, x_aligned) %>%
  mutate(operator_mean = mean(sig2, na.rm = T)) %>%
  ungroup() %>%
  ggplot() + 
  geom_line(aes(x = x_aligned, y = sig2, group = scan_id, color = factor(operator_code)), alpha = 0.7) + 
  geom_line(aes(x = x_aligned, y = operator_mean, group = operator_code), alpha = 0.7) + 
  theme_bw() + 
  #facet_wrap(~bullet, nrow = 3) + 
  labs(title = "Barrel Orange Land 6", x = "Relative X Location", y = "Signature Height") + 
  scale_color_discrete(name = "Operator ID")
```




```{r}
bo_long %>%
  filter(unique_id == "BL O-1") %>%
  group_by(machine, x_aligned) %>%
  mutate(machine_mean = mean(sig2, na.rm = T)) %>%
  ungroup() %>%
  ggplot() + 
  geom_line(aes(x = x_aligned, y = sig2, group = scan_id, color = factor(machine)), alpha = 0.7) + 
  geom_line(aes(x = x_aligned, y = machine_mean, group = machine), alpha = 0.7) + 
  theme_bw() + 
  #facet_wrap(~bullet, nrow = 3) + 
  labs(title = "Barrel Orange Land 1", x = "Relative X Location", y = "Signature Height") + 
  scale_color_discrete(name = "Machine ID")

bo_long %>%
  filter(unique_id == "BL O-2") %>%
  group_by(machine, x_aligned) %>%
  mutate(machine_mean = mean(sig2, na.rm = T)) %>%
  ungroup() %>%
  ggplot() + 
  geom_line(aes(x = x_aligned, y = sig2, group = scan_id, color = factor(machine)), alpha = 0.7) + 
  geom_line(aes(x = x_aligned, y = machine_mean, group = machine), alpha = 0.7) + 
  theme_bw() + 
  #facet_wrap(~bullet, nrow = 3) + 
  labs(title = "Barrel Orange Land 2", x = "Relative X Location", y = "Signature Height") + 
  scale_color_discrete(name = "Machine ID")

bo_long %>%
  filter(sig2 > -5, x_aligned < 2600, x_aligned > 10) %>%
  filter(unique_id == "BL O-3") %>%
  group_by(machine, x_aligned) %>%
  mutate(machine_mean = mean(sig2, na.rm = T)) %>%
  ungroup() %>%
  ggplot() + 
  geom_line(aes(x = x_aligned, y = sig2, group = scan_id, color = factor(machine)), alpha = 0.7) + 
  geom_line(aes(x = x_aligned, y = machine_mean, group = machine), alpha = 0.7) + 
  theme_bw() + 
  #facet_wrap(~bullet, nrow = 3) + 
  labs(title = "Barrel Orange Land 3", x = "Relative X Location", y = "Signature Height") + 
  scale_color_discrete(name = "Machine ID")

bo_long %>%
  filter(unique_id == "BL O-4") %>%
  group_by(machine, x_aligned) %>%
  mutate(machine_mean = mean(sig2, na.rm = T)) %>%
  ungroup() %>%
  ggplot() + 
  geom_line(aes(x = x_aligned, y = sig2, group = scan_id, color = factor(machine)), alpha = 0.7) + 
  geom_line(aes(x = x_aligned, y = machine_mean, group = machine), alpha = 0.7) + 
  theme_bw() + 
  #facet_wrap(~bullet, nrow = 3) + 
  labs(title = "Barrel Orange Land 4", x = "Relative X Location", y = "Signature Height") + 
  scale_color_discrete(name = "Machine ID")

bo_long %>%
  filter(unique_id == "BL O-5") %>%
  group_by(machine, x_aligned) %>%
  mutate(machine_mean = mean(sig2, na.rm = T)) %>%
  ungroup() %>%
  ggplot() + 
  geom_line(aes(x = x_aligned, y = sig2, group = scan_id, color = factor(machine)), alpha = 0.7) + 
  geom_line(aes(x = x_aligned, y = machine_mean, group = machine), alpha = 0.7) + 
  theme_bw() + 
  #facet_wrap(~bullet, nrow = 3) + 
  labs(title = "Barrel Orange Land 5", x = "Relative X Location", y = "Signature Height") + 
  scale_color_discrete(name = "Machine ID")

bo_long %>%
  filter(unique_id == "BL O-6") %>%
  group_by(machine, x_aligned) %>%
  mutate(machine_mean = mean(sig2, na.rm = T)) %>%
  ungroup() %>%
  ggplot() + 
  geom_line(aes(x = x_aligned, y = sig2, group = scan_id, color = factor(machine)), alpha = 0.7) + 
  geom_line(aes(x = x_aligned, y = machine_mean, group = machine), alpha = 0.7) + 
  theme_bw() + 
  #facet_wrap(~bullet, nrow = 3) + 
  labs(title = "Barrel Orange Land 6", x = "Relative X Location", y = "Signature Height") + 
  scale_color_discrete(name = "Machine ID")
```





```{r}
bo_long %>%
  filter(unique_id == "BL O-1") %>%
  group_by(bullet, x_aligned) %>%
  mutate(bullet_mean = mean(sig2, na.rm = T)) %>%
  ungroup() %>%
  ggplot() + 
  geom_line(aes(x = x_aligned, y = sig2, group = scan_id, color = factor(bullet)), alpha = 0.7) + 
  geom_line(aes(x = x_aligned, y = bullet_mean, group = bullet), alpha = 0.7) + 
  theme_bw() + 
  #facet_wrap(~bullet, nrow = 3) + 
  labs(title = "Barrel Orange Land 1", x = "Relative X Location", y = "Signature Height") + 
  scale_color_discrete(name = "Bullet ID")

bo_long %>%
  filter(unique_id == "BL O-2") %>%
  group_by(bullet, x_aligned) %>%
  mutate(bullet_mean = mean(sig2, na.rm = T)) %>%
  ungroup() %>%
  ggplot() + 
  geom_line(aes(x = x_aligned, y = sig2, group = scan_id, color = factor(bullet)), alpha = 0.7) + 
  geom_line(aes(x = x_aligned, y = bullet_mean, group = bullet), alpha = 0.7) + 
  theme_bw() + 
  #facet_wrap(~bullet, nrow = 3) + 
  labs(title = "Barrel Orange Land 2", x = "Relative X Location", y = "Signature Height")+ 
  scale_color_discrete(name = "Bullet ID")

bo_long %>%  
  filter(sig2 > -5, x_aligned < 2600, x_aligned > 10) %>%
  filter(unique_id == "BL O-3") %>%
  group_by(bullet, x_aligned) %>%
  mutate(bullet_mean = mean(sig2, na.rm = T)) %>%
  ungroup() %>%
  ggplot() + 
  geom_line(aes(x = x_aligned, y = sig2, group = scan_id, color = factor(bullet)), alpha = 0.7) + 
  geom_line(aes(x = x_aligned, y = bullet_mean, group = bullet), alpha = 0.7) + 
  theme_bw() + 
  #facet_wrap(~bullet, nrow = 3) + 
  labs(title = "Barrel Orange Land 3", x = "Relative X Location", y = "Signature Height")+ 
  scale_color_discrete(name = "Bullet ID")

bo_long %>%
  filter(unique_id == "BL O-4") %>%
  group_by(bullet, x_aligned) %>%
  mutate(bullet_mean = mean(sig2, na.rm = T)) %>%
  ungroup() %>%
  ggplot() + 
  geom_line(aes(x = x_aligned, y = sig2, group = scan_id, color = factor(bullet)), alpha = 0.7) + 
  geom_line(aes(x = x_aligned, y = bullet_mean, group = bullet), alpha = 0.7) + 
  theme_bw() + 
  #facet_wrap(~bullet, nrow = 3) + 
  labs(title = "Barrel Orange Land 4", x = "Relative X Location", y = "Signature Height")+ 
  scale_color_discrete(name = "Bullet ID")

bo_long %>%
  filter(unique_id == "BL O-5") %>%
  group_by(bullet, x_aligned) %>%
  mutate(bullet_mean = mean(sig2, na.rm = T)) %>%
  ungroup() %>%
  ggplot() + 
  geom_line(aes(x = x_aligned, y = sig2, group = scan_id, color = factor(bullet)), alpha = 0.7) + 
  geom_line(aes(x = x_aligned, y = bullet_mean, group = bullet), alpha = 0.7) + 
  theme_bw() + 
  #facet_wrap(~bullet, nrow = 3) + 
  labs(title = "Barrel Orange Land 5", x = "Relative X Location", y = "Signature Height")+ 
  scale_color_discrete(name = "Bullet ID")

bo_long %>%
  filter(abs(sig2) < 20) %>%
  filter(unique_id == "BL O-6") %>%
  group_by(bullet, x_aligned) %>%
  mutate(bullet_mean = mean(sig2, na.rm = T)) %>%
  ungroup() %>%
  ggplot() + 
  geom_line(aes(x = x_aligned, y = sig2, group = scan_id, color = factor(bullet)), alpha = 0.7) + 
  geom_line(aes(x = x_aligned, y = bullet_mean, group = bullet), alpha = 0.7) + 
  theme_bw() + 
  #facet_wrap(~bullet, nrow = 3) + 
  labs(title = "Barrel Orange Land 6", x = "Relative X Location", y = "Signature Height")+ 
  scale_color_discrete(name = "Bullet ID")
```







## Taking a look at the residuals

```{r}
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")


sigs_long_plot <- bo_long %>%
  filter(unique_id == "BL O-2", sig2 >= -5) %>%
  group_by(x_aligned) %>%
  mutate(mean_all = mean(sig2, na.rm = T), resid_all = sig2 - mean_all) %>%
  ungroup() %>%
  group_by(x_aligned, bullet) %>%
  mutate(mean_bullet = mean(sig2, na.rm = T), resid_bullet = sig2 - mean_bullet) %>%
  ungroup() %>%
  group_by(x_aligned, bullet, operator) %>%
  mutate(mean_operator_nest = mean(sig2, na.rm = T), resid_operator_nest = sig2 - mean_operator_nest) %>%
  ungroup() %>%
  group_by(x_aligned, bullet, operator, machine) %>%
  mutate(mean_machine_nest = mean(sig2, na.rm = T), resid_machine_nest = sig2 - mean_machine_nest) %>%
  ungroup() 


sigs_long_plot %>%
  filter(operator != "Allison") %>%
  group_by(x_aligned, bullet) %>%
  mutate(value_min = min(sig2, na.rm = T), 
            value_max = max(sig2, na.rm = T),
          max_bullet = max(resid_bullet, na.rm = T), 
         min_bullet = min(resid_bullet, na.rm = T)) %>% 
  ungroup() %>%
  ggplot() + 
  geom_ribbon(aes(x = x_aligned, ymin = min_bullet, ymax = max_bullet, fill = factor(bullet)), alpha = 0.4) + 
  geom_line(aes(x = x_aligned, y = sig2 + 10 , group = scan_id, color = factor(bullet)), alpha = 0.6) + 
  geom_hline(yintercept = 0) + 
  #geom_line(aes(x = x_aligned, y = mean_bullet, group = bullet), alpha = 0.8) + 
  theme_bw() + 
  labs(x = "X Location", y = "Signature height", title = "Residuals: Mean by bullet of Barrel Orange-Land 3") + 
  scale_color_manual(name = "Bullet", values = cbPalette[c(2,3,7)]) + 
  scale_fill_manual(name = "Bullet", values = cbPalette[c(2,3,7)]) + 
  theme(legend.position = "bottom") + 
  ylim(c(-5, 16)) + 
  facet_wrap(~bullet, nrow =3)
```







