---
title: "variability data grooves, signature extraction"
output: html_document
---


First, read in the packages.  

```{r packages, echo = F, warning = F, message = F}
library(tidyverse)
library(bulletxtrctr)
library(x3ptools)
```


## BARREL ORANGE  
Crosscut data already extracted  

```{r}
orange_r1 <- readRDS("../data/variability_scans/Orange_round1_cc_update.rda")
orange_r2 <- readRDS("../data/variability_scans/Orange_round2_cc_update.rda")
orange_r3 <- readRDS("../data/variability_scans/Orange_round3_cc_update.rda")
orange_r4 <- readRDS("../data/variability_scans/Orange_round4_cc_update.rda")
orange_r5 <- readRDS("../data/variability_scans/Orange_round5_cc_update.rda")
orange_r6 <- readRDS("../data/variability_scans/Orange_round6_cc_update.rda")
orange_all <- rbind(orange_r1, orange_r2, orange_r3, orange_r4, orange_r5, orange_r6)


scan_filters <- readRDS("../data/scans_to_filter_out.rda")
scan_renames <- read_csv("../data/scans_to_rename_updates.csv")
`%notin%` = Negate(`%in%`)

orange_all <- orange_all %>% filter(source %notin% scan_filters)
orange_all <- left_join(orange_all, scan_renames)
orange_all <- orange_all %>% mutate(barrel = ifelse(is.na(barrel_updated), barrel, barrel_updated), 
                                      bullet = ifelse(is.na(bullet_updated), bullet, bullet_updated), 
                                      machine = ifelse(is.na(machine_updated), machine, machine_updated))

#orange_all %>% group_by(operator, bullet, machine, round) %>% summarise(n=n())

orange_all <- orange_all %>% 
  mutate(scan_id = paste0(barrel, "-", land, "-", bullet, "-", 
                          operator, "-", machine, "-", round))
orange_all <- orange_all %>% select(-c(barrel_updated, bullet_updated, machine_updated, crosscut_safe))

#saveRDS(orange_all, "../data/variability_scans/Orange_all_cc_updated.rda")
orange_crosscuts <- readRDS("../data/variability_scans/Orange_all_cc_updated.rda")


orange_crosscuts <- orange_crosscuts %>% mutate(
  grooves = ccdata %>% 
    purrr::map(.f = cc_locate_grooves, method = "lassofull", 
               adjust = 10, return_plot = TRUE)
)
```

```{r}
ccdata <- orange_crosscuts$ccdata
grooves <- orange_crosscuts$grooves



library(shiny)

#if (interactive()) {
shinyApp(
  
  ui = fluidPage(
    selectInput("k","Investigate kth plot:", selected = 1,
                choices=1:length(grooves)),
    textOutput("groovelocations"),
    actionButton("confirm", "Confirm"),
    actionButton("save", "Save"),
    plotOutput("groovePlot", click = "plot_click"),
    verbatimTextOutput("info")
  ),
  
  server = function(input, output, session) {
    output$groovePlot <- renderPlot({
      k <- as.numeric(input$k)
      p <- grooves[[k]]$plot 

      p
    })
    output$groovelocations <- renderText({
      paste("Left Groove: ",grooves[[as.numeric(input$k)]]$groove[1], 
            " Right Groove: ",grooves[[as.numeric(input$k)]]$groove[2])
    })
    observeEvent(input$confirm,{
      cat(str(input$k))
      updateSelectInput(session, "k","Investigate kth plot:", 
                        selected = as.numeric(input$k)+1,
                        choices=1:length(grooves))
    })
    observeEvent(input$save,{
      saveRDS(grooves, file="../data/variability_scans/Orange_all_grooves_updated.rda")
      cat("groove data saved\n")
    })
    
    observeEvent(input$plot_click,{
      k <- as.numeric(input$k)
      xloc <- input$plot_click$x
      
      gr <- grooves[[k]]$groove
      if (abs(gr[1]-xloc) < abs(gr[2]-xloc)) {
        grooves[[k]]$groove[1] <<- xloc
      } else {
        grooves[[k]]$groove[2] <<- xloc
      }
      output$groovePlot <- renderPlot({ 
      k <- as.numeric(input$k)
      p <- grooves[[k]]$plot + 
        geom_vline(xintercept = grooves[[k]]$groove[1], colour="green") +
        geom_vline(xintercept = grooves[[k]]$groove[2], colour="green")
    
      p
      })
  
    })
    output$info <- renderText({
    paste0("x=", input$plot_click$x, "\ny=", input$plot_click$y)
  })

  },
  
  options = list(height = 500)
)
#}
#saveRDS(grooves, file="../data/variability_scans/Orange_all_grooves_updated.rda")

```

```{r}
grooves <- readRDS("../data/variability_scans/Orange_all_grooves_updated.rda")
orange_crosscuts$grooves <- grooves


orange_crosscuts <- orange_crosscuts %>% mutate(
  sigs = purrr::map2(
    .x = ccdata, .y = grooves, 
    .f = function(x, y) {
      cc_get_signature(
        ccdata = x, grooves = y, span1 = 0.75, span2 = 0.03)
    })
)

orange_sigs <- orange_crosscuts %>% select(-ccdata)

orange_sigs <- orange_sigs %>% mutate(grooves = purrr::map(grooves, .f = function(x) x$groove))

saveRDS(orange_sigs, "../data/variability_scans/Orange_all_sigs_updated.rda")
```




## BARREL GREEN  

Crosscut data already extracted  

```{r}
green_r1 <- readRDS("../data/variability_scans/Green_round1_cc.rda")
green_r2 <- readRDS("../data/variability_scans/Green_round2_cc.rda")
green_r3 <- readRDS("../data/variability_scans/Green_round3_cc.rda")
green_r4 <- readRDS("../data/variability_scans/Green_round4_cc.rda")
green_r5 <- readRDS("../data/variability_scans/Green_round5_cc.rda")
green_all <- rbind(green_r1, green_r2, green_r3, green_r4, green_r5)
#saveRDS(green_all, "../data/variability_scans/Green_all_cc.rda")
green_crosscuts <- readRDS("../data/variability_scans/Green_all_cc.rda")

green_crosscuts <- green_crosscuts %>% 
  mutate(scan_id = paste0(barrel, "-", land, "-", bullet, "-", 
                          operator, "-", machine, "-", round))


green_crosscuts <- green_crosscuts %>% mutate(
  grooves = ccdata %>% 
    purrr::map(.f = cc_locate_grooves, method = "lassofull", 
               adjust = 10, return_plot = TRUE)
)
```

```{r}
ccdata <- green_crosscuts$ccdata
grooves <- green_crosscuts$grooves



library(shiny)

#if (interactive()) {
shinyApp(
  
  ui = fluidPage(
    selectInput("k","Investigate kth plot:", selected = 1,
                choices=1:length(grooves)),
    textOutput("groovelocations"),
    actionButton("confirm", "Confirm"),
    actionButton("save", "Save"),
    plotOutput("groovePlot", click = "plot_click"),
    verbatimTextOutput("info")
  ),
  
  server = function(input, output, session) {
    output$groovePlot <- renderPlot({
      k <- as.numeric(input$k)
      p <- grooves[[k]]$plot 

      p
    })
    output$groovelocations <- renderText({
      paste("Left Groove: ",grooves[[as.numeric(input$k)]]$groove[1], 
            " Right Groove: ",grooves[[as.numeric(input$k)]]$groove[2])
    })
    observeEvent(input$confirm,{
      cat(str(input$k))
      updateSelectInput(session, "k","Investigate kth plot:", 
                        selected = as.numeric(input$k)+1,
                        choices=1:length(grooves))
    })
    observeEvent(input$save,{
      saveRDS(grooves, file="../data/variability_scans/Green_all_grooves.rda")
      cat("groove data saved\n")
    })
    
    observeEvent(input$plot_click,{
      k <- as.numeric(input$k)
      xloc <- input$plot_click$x
      
      gr <- grooves[[k]]$groove
      if (abs(gr[1]-xloc) < abs(gr[2]-xloc)) {
        grooves[[k]]$groove[1] <<- xloc
      } else {
        grooves[[k]]$groove[2] <<- xloc
      }
      output$groovePlot <- renderPlot({ 
      k <- as.numeric(input$k)
      p <- grooves[[k]]$plot + 
        geom_vline(xintercept = grooves[[k]]$groove[1], colour="green") +
        geom_vline(xintercept = grooves[[k]]$groove[2], colour="green")
    
      p
      })
  
    })
    output$info <- renderText({
    paste0("x=", input$plot_click$x, "\ny=", input$plot_click$y)
  })

  },
  
  options = list(height = 500)
)
#}
#saveRDS(grooves, file="../data/variability_scans/Green_all_grooves.rda")

```



```{r}
green_grooves <- readRDS("../data/variability_scans/Green_all_grooves.rda")
green_crosscuts$grooves <- green_grooves


green_crosscuts <- green_crosscuts %>% mutate(
  sigs = purrr::map2(
    .x = ccdata, .y = grooves, 
    .f = function(x, y) {
      cc_get_signature(
        ccdata = x, grooves = y, span1 = 0.75, span2 = 0.03)
    })
)

green_sigs <- green_crosscuts %>% select(-ccdata)
saveRDS(green_sigs, "../data/variability_scans/Green_all_sigs.rda")
```



## BARREL PINK  

Crosscut data already extracted  

```{r}
pink_r1 <- readRDS("../data/variability_scans/Pink_round1_cc_update.rda")
pink_r2 <- readRDS("../data/variability_scans/Pink_round2_cc_update.rda")
pink_r3 <- readRDS("../data/variability_scans/Pink_round3_cc_update.rda")
pink_r4 <- readRDS("../data/variability_scans/Pink_round4_cc_update.rda")
pink_r5 <- readRDS("../data/variability_scans/Pink_round5_cc_update.rda")
pink_r6 <- readRDS("../data/variability_scans/Pink_round6_cc_update.rda")
pink_all <- rbind(pink_r1, pink_r2, pink_r3, pink_r4, pink_r5, pink_r6)

scan_filters <- readRDS("../data/scans_to_filter_out.rda")
scan_renames <- read_csv("../data/scans_to_rename_updates.csv")
`%notin%` = Negate(`%in%`)

pink_all <- pink_all %>% filter(source %notin% scan_filters)
pink_all <- left_join(pink_all, scan_renames)
pink_all <- pink_all %>% mutate(barrel = ifelse(is.na(barrel_updated), barrel, barrel_updated), 
                                      bullet = ifelse(is.na(bullet_updated), bullet, bullet_updated), 
                                      machine = ifelse(is.na(machine_updated), machine, machine_updated))

#pink_all %>% group_by(operator, bullet, machine, round) %>% summarise(n=n())

pink_all <- pink_all %>% 
  mutate(scan_id = paste0(barrel, "-", land, "-", bullet, "-", 
                          operator, "-", machine, "-", round))
pink_all <- pink_all %>% select(-c(barrel_updated, bullet_updated, machine_updated, crosscut_safe))


#saveRDS(pink_all, "../data/variability_scans/Pink_all_cc_updated.rda")
pink_crosscuts <- readRDS("../data/variability_scans/Pink_all_cc_updated.rda")

pink_crosscuts <- pink_crosscuts %>% mutate(
  grooves = ccdata %>% 
    purrr::map(.f = cc_locate_grooves, method = "lassofull", 
               adjust = 10, return_plot = TRUE)
)
```

```{r}
ccdata <- pink_crosscuts$ccdata
grooves <- pink_crosscuts$grooves



library(shiny)

#if (interactive()) {
shinyApp(
  
  ui = fluidPage(
    selectInput("k","Investigate kth plot:", selected = 1,
                choices=1:length(grooves)),
    textOutput("groovelocations"),
    actionButton("confirm", "Confirm"),
    actionButton("save", "Save"),
    plotOutput("groovePlot", click = "plot_click"),
    verbatimTextOutput("info")
  ),
  
  server = function(input, output, session) {
    output$groovePlot <- renderPlot({
      k <- as.numeric(input$k)
      p <- grooves[[k]]$plot 

      p
    })
    output$groovelocations <- renderText({
      paste("Left Groove: ",grooves[[as.numeric(input$k)]]$groove[1], 
            " Right Groove: ",grooves[[as.numeric(input$k)]]$groove[2])
    })
    observeEvent(input$confirm,{
      cat(str(input$k))
      updateSelectInput(session, "k","Investigate kth plot:", 
                        selected = as.numeric(input$k)+1,
                        choices=1:length(grooves))
    })
    observeEvent(input$save,{
      saveRDS(grooves, file="../data/variability_scans/Pink_all_grooves_updated.rda")
      cat("groove data saved\n")
    })
    
    observeEvent(input$plot_click,{
      k <- as.numeric(input$k)
      xloc <- input$plot_click$x
      
      gr <- grooves[[k]]$groove
      if (abs(gr[1]-xloc) < abs(gr[2]-xloc)) {
        grooves[[k]]$groove[1] <<- xloc
      } else {
        grooves[[k]]$groove[2] <<- xloc
      }
      output$groovePlot <- renderPlot({ 
      k <- as.numeric(input$k)
      p <- grooves[[k]]$plot + 
        geom_vline(xintercept = grooves[[k]]$groove[1], colour="green") +
        geom_vline(xintercept = grooves[[k]]$groove[2], colour="green")
    
      p
      })
  
    })
    output$info <- renderText({
    paste0("x=", input$plot_click$x, "\ny=", input$plot_click$y)
  })

  },
  
  options = list(height = 500)
)
#}
saveRDS(grooves, file="../data/variability_scans/Pink_all_grooves_updated.rda")

```

```{r}
pink_grooves <- readRDS("../data/variability_scans/Pink_all_grooves_updated.rda")
pink_crosscuts$grooves <- pink_grooves


pink_sigs <- pink_crosscuts %>% mutate(
  sigs = purrr::map2(
    .x = ccdata, .y = grooves, 
    .f = function(x, y) {
      cc_get_signature(
        ccdata = x, grooves = y, span1 = 0.75, span2 = 0.03)
    })
)

pink_sigs <- pink_sigs %>% mutate(grooves = purrr::map(grooves, .f = function(x) x$groove))
saveRDS(pink_sigs, "../data/variability_scans/Pink_all_sigs_updated.rda")
```




## BARREL BLUE

Crosscut data already extracted  

```{r}
blue_r1 <- readRDS("../data/variability_scans/Blue_round1_cc_update.rda")
blue_r2 <- readRDS("../data/variability_scans/Blue_round2_cc_update.rda")
blue_r3 <- readRDS("../data/variability_scans/Blue_round3_cc_update.rda")
blue_r4 <- readRDS("../data/variability_scans/Blue_round4_cc_update.rda")
blue_r5 <- readRDS("../data/variability_scans/Blue_round5_cc_update.rda")
blue_r6 <- readRDS("../data/variability_scans/Blue_round6_cc_update.rda")
blue_all <- rbind(blue_r1, blue_r2, blue_r3, blue_r4, blue_r5, blue_r6)

scan_filters <- readRDS("../data/scans_to_filter_out.rda")
scan_renames <- read_csv("../data/scans_to_rename_updates.csv")
`%notin%` = Negate(`%in%`)

blue_all <- blue_all %>% filter(source %notin% scan_filters)
blue_all <- left_join(blue_all, scan_renames)
blue_all <- blue_all %>% mutate(barrel = ifelse(is.na(barrel_updated), barrel, barrel_updated), 
                                      bullet = ifelse(is.na(bullet_updated), bullet, bullet_updated), 
                                      machine = ifelse(is.na(machine_updated), machine, machine_updated))

blue_all <- blue_all %>% 
  mutate(scan_id = paste0(barrel, "-", land, "-", bullet, "-", 
                          operator, "-", machine, "-", round))
blue_all <- blue_all %>% select(-c(barrel_updated, bullet_updated, machine_updated, crosscut_safe))


#saveRDS(blue_all, "../data/variability_scans/Blue_all_cc_updated.rda")
blue_crosscuts <- readRDS("../data/variability_scans/Blue_all_cc_updated.rda")

blue_crosscuts <- blue_crosscuts %>% 
  mutate(scan_id = paste0(barrel, "-", land, "-", bullet, "-", 
                          operator, "-", machine, "-", round))

blue_crosscuts <- blue_crosscuts %>% mutate(
  grooves = ccdata %>% 
    purrr::map(.f = cc_locate_grooves, method = "lassofull", 
               adjust = 10, return_plot = TRUE)
)
```

```{r}
ccdata <- blue_crosscuts$ccdata
grooves <- blue_crosscuts$grooves



library(shiny)

#if (interactive()) {
shinyApp(
  
  ui = fluidPage(
    selectInput("k","Investigate kth plot:", selected = 1,
                choices=1:length(grooves)),
    textOutput("groovelocations"),
    actionButton("confirm", "Confirm"),
    actionButton("save", "Save"),
    plotOutput("groovePlot", click = "plot_click"),
    verbatimTextOutput("info")
  ),
  
  server = function(input, output, session) {
    output$groovePlot <- renderPlot({
      k <- as.numeric(input$k)
      p <- grooves[[k]]$plot 

      p
    })
    output$groovelocations <- renderText({
      paste("Left Groove: ",grooves[[as.numeric(input$k)]]$groove[1], 
            " Right Groove: ",grooves[[as.numeric(input$k)]]$groove[2])
    })
    observeEvent(input$confirm,{
      cat(str(input$k))
      updateSelectInput(session, "k","Investigate kth plot:", 
                        selected = as.numeric(input$k)+1,
                        choices=1:length(grooves))
    })
    observeEvent(input$save,{
      saveRDS(grooves, file="../data/variability_scans/Blue_all_grooves_updated.rda")
      cat("groove data saved\n")
    })
    
    observeEvent(input$plot_click,{
      k <- as.numeric(input$k)
      xloc <- input$plot_click$x
      
      gr <- grooves[[k]]$groove
      if (abs(gr[1]-xloc) < abs(gr[2]-xloc)) {
        grooves[[k]]$groove[1] <<- xloc
      } else {
        grooves[[k]]$groove[2] <<- xloc
      }
      output$groovePlot <- renderPlot({ 
      k <- as.numeric(input$k)
      p <- grooves[[k]]$plot + 
        geom_vline(xintercept = grooves[[k]]$groove[1], colour="green") +
        geom_vline(xintercept = grooves[[k]]$groove[2], colour="green")
    
      p
      })
  
    })
    output$info <- renderText({
    paste0("x=", input$plot_click$x, "\ny=", input$plot_click$y)
  })

  },
  
  options = list(height = 500)
)
#}
saveRDS(grooves, file="../data/variability_scans/Blue_all_grooves_updated.rda")

```

```{r}
blue_grooves <- readRDS("../data/variability_scans/Blue_all_grooves_updated.rda")
blue_crosscuts$grooves <- blue_grooves


blue_crosscuts <- blue_crosscuts %>% mutate(
  sigs = purrr::map2(
    .x = ccdata, .y = grooves, 
    .f = function(x, y) {
      cc_get_signature(
        ccdata = x, grooves = y, span1 = 0.75, span2 = 0.03)
    })
)

blue_sigs <- blue_crosscuts %>% select(-ccdata)



blue_sigs <- blue_sigs %>% mutate(grooves = purrr::map(grooves, .f = function(x) x$groove))
saveRDS(blue_sigs, "../data/variability_scans/Blue_all_sigs_updated.rda")
```

