---
title: "Untitled"
output: html_document
---

```{r}
orange_meta <- readRDS("../data/variability_scans/orange_metadata.rda")
green_meta <- readRDS("../data/variability_scans/green_metadata.rda")
pink_meta <- readRDS("../data/variability_scans/pink_metadata.rda")
scan_meta <- rbind(orange_meta, green_meta, pink_meta)
operators <- read_csv("../data/variability_scans/operators_blind.csv")
scan_meta <- left_join(scan_meta, operators)

scan_meta %>%
  mutate(date_time = paste0(date, " ", time),
         date_time = lubridate::ymd_hms(date_time), 
         date = lubridate::ymd(date), 
         time = lubridate::hms(time)) %>%
  group_by(date, round, operator_code) %>%
  summarise(n_scans = n()) %>%
  ggplot() + 
  geom_point(aes(x = date, y = round, color = factor(operator_code), size = n_scans), alpha = 0.7) + 
  theme_bw() + 
  facet_wrap(~operator_code, nrow = 5) + 
  labs(x = "Date", y = "Round Number") + 
  scale_size_continuous(name = "Number of Scans") + 
  scale_color_discrete(name = "Operator")

scan_meta %>%
  mutate(date_time = paste0(date, " ", time),
         date_time = lubridate::ymd_hms(date_time), 
         date = lubridate::ymd(date), 
         time = lubridate::hms(time)) %>%
  group_by(date, round, operator_code) %>%
  summarise(n_scans = n()) %>%
  ggplot() + 
  geom_point(aes(x = date, y = operator_code, color = factor(operator_code), size = n_scans), alpha = 0.7) + 
  theme_bw() + 
  facet_wrap(~round, nrow = 5) + 
  labs(x = "Date", y = "Operator") + 
  scale_size_continuous(name = "Number of Scans") + 
  scale_color_discrete(name = "Operator")
```


```{r}
scan_meta %>%
  mutate(date_time = paste0(date, " ", time),
         date_time = lubridate::ymd_hms(date_time), 
         date = lubridate::ymd(date), 
         time = lubridate::hms(time)) %>%
  group_by(date, round, operator_code, barrel) %>%
  summarise(n_scans = n()) %>%
  ggplot() + 
  geom_jitter(aes(x = date, y = round, color = factor(barrel), size = n_scans), alpha = 0.7) + 
  theme_bw() + 
  facet_wrap(~operator_code, nrow = 5) + 
  scale_color_manual(name = "Barrel", breaks = c("Barrel Green", "Barrel Orange", "Barrel Pink"), values = c("forestgreen", "darkorange1", "hotpink3")) + 
  scale_size_continuous(name = "Number of Scans") + 
  labs(x = "Date", y = "Round") 
```


```{r}
scan_meta %>%
    mutate(date_time = paste0(date, " ", time),
           date_time = lubridate::ymd_hms(date_time), 
           date = lubridate::ymd(date), 
           time = hms::as.hms(time), 
           hour = lubridate::hour(time)) %>%
  ggplot() + 
  geom_histogram(aes(x = time, fill = factor(operator_code)),  position = "identity", alpha = 0.6) +
  theme_bw() + 
  labs(x = "Time of Day") + 
  scale_fill_discrete(name = "Operator")
```


```{r}
library(tidyverse)
library(bulletxtrctr)
library(x3ptools)
filenames <- list.files("/media/Raven/Variability/", pattern = "*.x3p", full.names = T, recursive = T)
scans <- data.frame(source = filenames)

scans <- scans %>%
  mutate(operator = purrr::map_chr(as.character(source), .f = function(filename){
    strsplit(strsplit(filename, "//")[[1]][2], "/")[[1]][1]
  }),
  round = purrr::map_chr(as.character(source), .f = function(filename){
    str_trim(strsplit(filename, "-")[[1]][2])
  }), 
  machine = purrr::map_chr(as.character(source), .f = function(filename){
    str_trim(strsplit(filename, "-")[[1]][6])
  }), 
  barrel = purrr::map_chr(as.character(source), .f = function(filename){
    str_trim(strsplit(filename, "-")[[1]][3])
  }), 
  bullet = purrr::map_chr(as.character(source), .f = function(filename){
    str_trim(strsplit(filename, "-")[[1]][4])
  }), 
  land = purrr::map_chr(as.character(source), .f = function(filename){
    str_trim(strsplit(filename, "-")[[1]][5])
  }))
scans %>% group_by(operator, machine, bullet, barrel, land) %>% summarise(n= n())
scans %>% filter(operator == "Anyesha") %>% group_by(machine, bullet, barrel, land) %>% summarise(n = n())

allison_issues <- scans %>% filter(operator == "Allison", (round == "Round 1" | round == "Round 2")) %>% pull(source)
marco_issues <- scans %>% filter(operator == "Marco", round == "Round 3", barrel == "Barrel Orange", bullet == "Bullet 2", machine == "Sneox2") %>% pull(source)
mark_issues1 <- scans %>% filter(operator == "Mark", round == "Round 4", (barrel == "Barrel Orange" | barrel == "Barrel Pink"), machine == "Sneox1") %>% pull(source)
mark_issues2 <- scans %>% filter(operator == "Mark", round == "Round 2", barrel == "Barrel Blue", machine == "Sneox1") %>% pull(source)
mya_issues <- scans %>% filter(operator == "Mya", round %in% c("Round 2", "Round 3"), barrel != "Barrel Blue") %>% pull(source)
samantha_issues <- scans %>% filter(operator == "Samantha", round == "Round 3", barrel == "Barrel Orange", bullet == "Bullet 3", machine == "Sneox2") %>% pull(source)

all_issues <- c(as.character(allison_issues), as.character(marco_issues), as.character(mark_issues1), as.character(mark_issues2), as.character(mya_issues), as.character(samantha_issues))

scan_issues <- scans %>% filter(source %in% all_issues)

scan_issues <- scan_issues %>% mutate(x3p = purrr::map(as.character(source), .f = function(filename){
  x3ptools::read_x3p(filename)
}))


scan_issues <- scan_issues %>% mutate(sizeX = purrr::map_dbl(x3p, .f = function(x3p){
  as.numeric(x3p$matrix.info$MatrixDimension$SizeX[[1]][1])
}), 
sizeY = purrr::map_dbl(x3p, .f = function(x3p){
  as.numeric(x3p$matrix.info$MatrixDimension$SizeY[[1]][1])
}), 
date = purrr::map_chr(x3p, .f = function(x3p){
  strsplit(x3p$general.info$Date[[1]][1], "T")[[1]][1]
}),
time = purrr::map_chr(x3p, .f = function(x3p){
  strsplit(x3p$general.info$Date[[1]][1], "T")[[1]][2]
}))

scan_issues %>% 
  filter(source %in% allison_issues) %>% 
  select(-x3p) %>% 
  group_by(date, time) %>%
  mutate(n = n()) %>%
  ungroup() %>%
  #arrange(desc(n), date, time) %>%
  select(source, sizeX, sizeY, date, time, n) %>%
  filter(str_detect(source, "Round 1") == T) %>%
  arrange(source, date)

scan_issues %>% 
  filter(source %in% marco_issues) %>% 
  select(-x3p) %>% 
  group_by(date, time) %>%
  mutate(n = n()) %>%
  ungroup() %>%
  arrange(desc(n), date, time) %>%
  select(source, sizeX, sizeY, date, time, n) 

scan_issues %>% 
  filter(source %in% mark_issues1) %>%
  select(-x3p) %>%
  group_by(date, time) %>% 
  mutate(n = n()) %>%
  ungroup() %>%
  arrange(desc(n), date, time) %>%
  select(source, sizeX, sizeY, date, time, n)

scan_issues %>% 
  filter(source %in% mark_issues2) %>%
  select(-x3p) %>%
  group_by(date, time) %>% 
  mutate(n = n()) %>%
  ungroup() %>%
  arrange(desc(n), date, time) %>%
  select(source, sizeX, sizeY, date, time, n)


scan_issues %>% 
  filter(source %in% mya_issues) %>%
  select(-x3p) %>%
  group_by(date, time) %>% 
  mutate(n = n()) %>%
  ungroup() %>%
  arrange(desc(n), date, time) %>%
  select(source, sizeX, sizeY, date, time, n)

scan_issues %>% 
  filter(source %in% samantha_issues) %>%
  select(-x3p) %>%
  group_by(date, time) %>% 
  mutate(n = n()) %>%
  ungroup() %>%
  arrange(desc(n), date, time) %>%
  select(source, sizeX, sizeY, date, time, n)

```