---
title: "user measurements"
output: html_document
---

First, read in the packages.  

```{r packages, echo = F, warning = F, message = F}
library(tidyverse)
library(bulletxtrctr)
library(x3ptools)
library(gridExtra)
```

Read in the data, and extract Operator, Barrel, Bullet, and Land.  

```{r}
filenames <- list.files("/media/Sunny/CSAFE/User comparison scans/", pattern = "*.x3p", full.names = T, recursive = T)
user_meas <- data.frame(source = filenames)
user_meas <- user_meas %>% mutate(x3p = purrr::map(as.character(source), .f = function(filename){
  x3ptools::read_x3p(filename)
}))

user_meas <- user_meas %>% mutate(source = purrr::map_chr(as.character(source), .f = function(source){
  strsplit(source, "//")[[1]][2]
}))


user_meas <- user_meas %>% mutate(Round = purrr::map_chr(as.character(source), .f = function(source){
  strsplit(source, "/")[[1]][1]
}), 
Operator = purrr::map_chr(as.character(source), .f = function(source){
  op <- strsplit(source, "/")[[1]][2]
  strsplit(op, " ")[[1]][1]
}), 
source = factor(str_replace_all(source, ";", " -")),
Barrel = purrr::map_chr(as.character(source), .f = function(source){
  strsplit(source, " - ")[[1]][2]
}), 
Bullet = purrr::map_chr(as.character(source), .f = function(source){
  strsplit(source, " - ")[[1]][3]
}), 
Land = purrr::map_chr(as.character(source), .f = function(source){
  strsplit(source, " - ")[[1]][4]
}), 
Machine = purrr::map_chr(as.character(source), .f = function(source){
  mac <- ifelse(str_detect(source, "Scan") == T, strsplit(source, " - ")[[1]][6], strsplit(source, " - ")[[1]][5]) 
  str_replace_all(mac, " ", "")
}), 
Scan = purrr::map_chr(as.character(source), .f = function(source){
  ifelse(str_detect(source, "Scan") == T, strsplit(source, " - ")[[1]][5], "Scan 1")
}))


#head(user_meas)
```


Save just the information about the study set up.  
```{r, echo = F, warning = F, message = F}
user_setup <- user_meas %>% select(source, Round, Operator, Barrel, Bullet, Land, Machine, Scan)
#saveRDS(user_setup, "../data/user_meas_setup.rda")

```


Extract ccdata from each of the x3p files.  
```{r, echo = F, warning = F, message = F}
user_meas <- user_meas %>% mutate(ccdata = purrr::map(x3p, .f = function(x3p){
  x3ptools::x3p_to_df(x3p)
}))

user_ccdata <- user_meas %>% select(source, Round, Operator, Barrel, Bullet, Land, Machine, Scan, ccdata)
#saveRDS(user_ccdata, "../data/user_meas_ccdata.rda")
```


```{r, echo = F, warning = F, message = F}
user_crosscuts <- user_meas %>% mutate(
  crosscut = purrr::map_dbl(x3p, .f = x3p_crosscut_optimize)
)

### REALLY IMPORTANT NOTE: 
### Some of the x3p files returned with NA values for the optimal crosscut.
### We will be imputing the median optimal crosscut for the other x3p files.  

user_crosscuts <- user_crosscuts %>% mutate(crosscut = ifelse(is.na(crosscut), median(crosscut, na.rm = T), crosscut))

user_crosscuts_recap <- user_crosscuts %>% filter(Round == "Round 4")

ccdata_ten_crosscut <- function(ccdata, y = NULL, range = 1e-05){
  #x3pdat <- bulletxtrctr::check_x3p(x3p)
  x3p_df <- na.trim(ccdata)
  ys <- unique(x3p_df$y)
  if (is.null(y))
    y <- median(ys)
  ind <- which.min(abs(y - ys))
  y_min <- ys[ind - 5]
  y_max <- ys[ind + 4]
  lower <- min(y_min, y_max)
  upper <- max(y_min, y_max)
  x3p_df_fix <- x3p_df[x3p_df$y >= lower & x3p_df$y <= upper,]
  return(na.omit(x3p_df_fix))
}
# now extract the crosscuts
user_crosscuts <- user_crosscuts %>% mutate(
  ccdata = purrr::map2(.x = ccdata, .y = crosscut, 
                       .f = ccdata_ten_crosscut)
)

user_crosscuts <- user_crosscuts %>% mutate(
  ccdata = purrr::map(ccdata, .f = function(ccdata){
    ccdata %>% group_by(x) %>% summarise(y = mean(y, na.rm = T), value = mean(value, na.rm = T))
  })
)

user_crosscuts <- user_crosscuts %>% select(-x3p)
#saveRDS(user_crosscuts, "../data/user_crosscuts.rda")
```

A section to extract crosscuts for recapture data, forcing the crosscuts to be the same!  

```{r}
user_crosscuts_recap <- user_crosscuts_recap %>% 
  mutate(scan_id = paste0(Barrel, "-", Land, "-", Bullet, "-", 
                          Operator, "-", Machine, "-", Round))

user_crosscuts_recap <- user_crosscuts_recap %>% 
  group_by(scan_id) %>% 
  mutate(crosscut = min(crosscut)) %>%
  ungroup()


user_crosscuts_recap <- user_crosscuts_recap %>% mutate(
  ccdata = purrr::map2(.x = ccdata, .y = crosscut, 
                       .f = ccdata_ten_crosscut)
)

user_crosscuts_recap <- user_crosscuts_recap %>% mutate(
  ccdata = purrr::map(ccdata, .f = function(ccdata){
    ccdata %>% group_by(x) %>% summarise(y = mean(y, na.rm = T), value = mean(value, na.rm = T))
  })
)

user_crosscuts_recap <- user_crosscuts_recap %>% select(-x3p)
saveRDS(user_crosscuts_recap, "../data/user_crosscuts_recap.rda")
```


